### ISSUE TITLE
 CleanUp failed Error: Received #1044 error from MySQL server: "Access denied for user ''@'10.%.%.%' to database 'optimizer_fkkV2wd427Mm7lwQ'"

### ISSUE THREAD

**Issue by 90wukai** [influx-code/iysql#1]
```
2018/10/25 16:37:07.650 [E] [env.go:143] CleanUp failed Error: Received #1044 error from MySQL server: "Access denied for user ''@'ip.%.%.%' to database 'optimizer_fkkV2wd427Mm7lwQ'"
```

需要额外的权限？

**Comment by Ilcyb** [comment]
> ```
> 2018/10/25 16:37:07.650 [E] [env.go:143] CleanUp failed Error: Received #1044 error from MySQL server: "Access denied for user 'jr_app_w'@'10.%.%.%' to database 'optimizer_fkkV2wd427Mm7lwQ'"
> ```
> 需要额外的权限？

iysql不需要其他权限，你这个问题可能是因为你的这个mysql账户在你的iysql所部署的机器所在的网络对你操作的数据库没有权限
