### ISSUE TITLE
[E] [soar.go:360] Profiling Error: TestDsn Disable

### ISSUE THREAD

**Issue by Jetereting** [influx-code/iysql#10]
![image](https://user-images.githubusercontent.com/11585188/47777076-e54c0a00-dd2e-11e8-8db3-0d05e62d3b3e.png)

是我哪里的配置有问题吗？测试连接是成功的

**Comment by Ilcyb** [comment]
> ![image](https://user-images.githubusercontent.com/11585188/47777076-e54c0a00-dd2e-11e8-8db3-0d05e62d3b3e.png)
> 
> 是我哪里的配置有问题吗？测试连接是成功的

你有没有单独的给你的soar写过配置文件呢，我的猜想是你写了单独的soar的配置文件，然后里面配置了禁止使用testdsn

**Comment by Jetereting** [comment]
> > ![image](https://user-images.githubusercontent.com/11585188/47777076-e54c0a00-dd2e-11e8-8db3-0d05e62d3b3e.png)
> > 是我哪里的配置有问题吗？测试连接是成功的
> 
> 你有没有单独的给你的soar写过配置文件呢，我的猜想是你写了单独的soar的配置文件，然后里面配置了禁止使用testdsn

是的 但是我尝试了改为：
online-dsn:
  disable: true
test-dsn:
 disable: true
重启还是这个错误，然后删掉配置文件 重启 还是这个错误

**Comment by Ilcyb** [comment]
@Jetereting 
1. 确认你在使用iysql时数据库地址，用户，密码等都填写正确了
2. 检查一下mysql的版本，如果是5.6的话，升级到5.7

**Comment by Jetereting** [comment]
> @Jetereting
> 
> 1. 确认你在使用iysql时数据库地址，用户，密码等都填写正确了
> 2. 检查一下mysql的版本，如果是5.6的话，升级到5.7

1.重新检查了下界面上的配置，没有空格，正确 而且测试连接也通过了
2.mysql 是 5.7.24-0ubuntu0.16.04.1-log 的

**Comment by ty4z2008** [comment]
这是因为你有配置把`test-dsn`的disable设置为了`true`

参考：https://github.com/XiaoMi/soar/blob/master/database/profiling.go#L53

**Comment by Jetereting** [comment]
> https://github.com/XiaoMi/soar/blob/master/database/profiling.go#L53

![image](https://user-images.githubusercontent.com/11585188/47828331-94372700-ddbd-11e8-9c8a-5be0a45e5311.png)

我是我确实尝试了只保留了一个 soar.yaml (跟soar可执行文件同目录) 并且 disable都为 false了

**Comment by xEdenx** [comment]
未添加配置文件时出现同样的问题 添加配置文件后设置成false也不行

**Comment by ty4z2008** [comment]
> 未添加配置文件时出现同样的问题 添加配置文件后设置成false也不行

贴一下你写的配置文件

**Comment by xEdenx** [comment]
![image](https://user-images.githubusercontent.com/7685451/48930652-ee468a80-ef2c-11e8-88a3-f22308c86598.png)


> > 未添加配置文件时出现同样的问题 添加配置文件后设置成false也不行
> 
> 贴一下你写的配置文件

mysql 5.7 连接测试成功

**Comment by ty4z2008** [comment]
@Tneciv 
```
echo "select title from sakila.film" | soar -test-dsn="root:123456@127.0.0.1:3306/sakila" -allow-online-as-test -log-output=soar.log

```
把上面的SQL和数据库配置改成你的配置，看看日志是什么

**Comment by xEdenx** [comment]
> @Tneciv
> 
> ```
> echo "select title from sakila.film" | soar -test-dsn="root:123456@127.0.0.1:3306/sakila" -allow-online-as-test -log-output=soar.log
> ```
> 把上面的SQL和数据库配置改成你的配置，看看日志是什么

[root@qtjifen ~]# echo "select open_id from oauth.user" | soar -test-dsn="root:******@127.0.0.1:3306/oauth" -allow-online-as-test -log-output=soar.log
# Query: 69468E426EA85199

★ ★ ★ ★ ☆ 80分

```sql

SELECT  
  open_id  
FROM  
  oauth. USER
```

##  最外层SELECT未指定WHERE条件

* **Item:**  CLA.001

* **Severity:**  L4

* **Content:**  SELECT语句没有WHERE子句，可能检查比预期更多的行(全表扫描)。对于SELECT COUNT(\*)类型的请求如果不要求精度，建议使用SHOW TABLE STATUS或EXPLAIN替代。

**Comment by xEdenx** [comment]
@ty4z2008  怎么关闭了？有解决方法吗？

**Comment by ty4z2008** [comment]
@Tneciv 以为这个问题已经解决了。
我提供一个官方的配置。另外，建议把soar升级到最新版后再测试试试
```
# 这是一个配置文件例子
online-dsn:
    addr:     127.0.0.1:3306
    schema:   sakila
    user:     root
    password: "123456"
    disable:  false

test-dsn:
    addr:     127.0.0.1:3306
    schema:   sakila
    user:     root
    password: "123456"
    disable:  false

allow-online-as-test: true

log-level:  7
sampling: true
```

**Comment by xEdenx** [comment]
> @Tneciv 以为这个问题已经解决了。
> 我提供一个官方的配置。另外，建议把soar升级到最新版后再测试试试
> 
> ```
> # 这是一个配置文件例子
> online-dsn:
>     addr:     127.0.0.1:3306
>     schema:   sakila
>     user:     root
>     password: "123456"
>     disable:  false
> 
> test-dsn:
>     addr:     127.0.0.1:3306
>     schema:   sakila
>     user:     root
>     password: "123456"
>     disable:  false
> 
> allow-online-as-test: true
> 
> log-level:  7
> sampling: true
> ```

好的 我试试看 谢谢
