### ISSUE TITLE
配置了环境变量报错

### ISSUE THREAD

**Issue by ciweigg2** [influx-code/iysql#13]
Check install environment
soar is not set.Eg:
alias soar=/root/soar
export soar=/root/soar

**Comment by gangh** [comment]
> Check install environment
> soar is not set.Eg:
> alias soar=/root/soar
> export soar=/root/soar

将 soar 路径添加到 PATH
refer to: https://github.com/influx-code/iysql/issues/6#issuecomment-434557718

**Comment by no-serve-people** [comment]
ERROR: Could not find a version that satisfies the requirement greenlet==0.4.15 (from -r requirments.txt (line 10)) (from versions: none)
ERROR: No matching distribution found for greenlet==0.4.15 (from -r requirments.txt (line 10))  报错

> > Check install environment
> > soar is not set.Eg:
> > alias soar=/root/soar
> > export soar=/root/soar
> 
> 将 soar 路径添加到 PATH
> refer to: [#6 (comment)](https://github.com/influx-code/iysql/issues/6#issuecomment-434557718)

ERROR: Could not find a version that satisfies the requirement greenlet==0.4.15 (from -r requirments.txt (line 10)) (from versions: none)
ERROR: No matching distribution found for greenlet==0.4.15 (from -r requirments.txt (line 10))  报错如下
