### ISSUE TITLE
初始化脚本/scripts/init.sh执行失败

### ISSUE THREAD

**Issue by deprecate98** [influx-code/iysql#16]
哥，你的初始化文件/scripts/init.sh：
#!/bin/bash
set -eu
echo 'Check install environment'

NEEDED_COMMANDS="soar git"

for cmd in ${NEEDED_COMMANDS} ; do
        if ! command -v "${cmd}" &> /dev/null ; then
                echo -e "\033[91m${cmd} is not set.Eg:\nalias ${cmd}=/root/${cmd}\nexport ${cmd}=/root/${cmd}\033[0m"
                exit 1
        else
                echo "${cmd} is install."
        fi
done

app='.'
echo -e '\033[33mStart install python dependency\033[0m'
pip3 install -r requirments.txt
exit 0

这里的“NEEDED_COMMANDS="soar git”是啥意思？这个初始化脚本怎么也执行不成功

**Comment by Ilcyb** [comment]
检测你的环境里有没有git和soar这两个命令
