### ISSUE TITLE
soar 的report type最好使用markdown或者html

### ISSUE THREAD

**Issue by 90wukai** [influx-code/iysql#2]
refer to https://github.com/XiaoMi/soar/issues/37#issuecomment-432608809

**Comment by Ilcyb** [comment]
> refer to [XiaoMi/soar#37 (comment)](https://github.com/XiaoMi/soar/issues/37#issuecomment-432608809)

可以在 iysql/iysql/config/soar.py 下将`{
    	"-report-type":{
    		"type" : 1,
    		"default" : "text"
    	},`里的default更改为你想要的值

**Comment by 90wukai** [comment]
@Ilcyb ok,我试一下

**Comment by 90wukai** [comment]
可以更改，但是或许加上markdown的渲染就更好了
