### ISSUE TITLE
Could not find a version that satisfies the requirement itsdangerous==1.0.0

### ISSUE THREAD

**Issue by Jetereting** [influx-code/iysql#4]
![image](https://user-images.githubusercontent.com/11585188/47633824-49819900-db8a-11e8-93ec-a25fb5593b8d.png)

**Comment by Ilcyb** [comment]
@Jetereting 请提供一下你的python版本
`python3 --version`

**Comment by gangh** [comment]
@Jetereting @Ilcyb 
与版本无关, 是因为  itsdangerous==1.0.0 在 pypi 中已经删了,在 1.1.0 中默认算法又改回了SHA1 ,修改更新 requirements 中的该依赖配置,我这可以使用了
 
refer to: https://github.com/pallets/itsdangerous/blob/master/CHANGES.rst#version-100

**Comment by Jetereting** [comment]
> @Jetereting 请提供一下你的python版本
> `python3 --version`

Python 3.5.2

**Comment by Ilcyb** [comment]
@Jetereting 
的确是因为 @gangh 说的那样，是因为pypi没有itsdangerous的1.0.0版本了，我已经把itsdangerous的版本改为1.1.0，你拉取一下最新的代码即可

**Comment by Jetereting** [comment]
> @Jetereting
> 的确是因为 @gangh 说的那样，是因为pypi没有itsdangerous的1.0.0版本了，我已经把itsdangerous的版本改为1.1.0，你拉取一下最新的代码即可

感谢 我重新 clone了下来 ，执行初始化脚本的时候 出现了新的错误：
![image](https://user-images.githubusercontent.com/11585188/47773081-dd3a9d00-dd23-11e8-86b8-45a5861da93e.png)

期间有段：  
Failed cleaning build dir for cryptography
  Running setup.py bdist_wheel for markupsafe ... done

**Comment by Ilcyb** [comment]
@Jetereting 
请根据你的系统安装对应的openssl依赖
https://cryptography.io/en/latest/installation/#building-cryptography-on-linux

**Comment by Jetereting** [comment]
> @Jetereting
> 请根据你的系统安装对应的openssl依赖
> https://cryptography.io/en/latest/installation/#building-cryptography-on-linux

Successfully installed asn1crypto-0.24.0 cffi-1.11.5 cryptography-2.3.1 enum34-1.1.6 idna-2.7 ipaddress-1.0.22 pycparser-2.19
看起来像是安装成功了，然后重新执行 ./scripts/init.sh

又出现了：
Command "/usr/bin/python3 -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-m9flflvy/cryptography/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-e1l3nj8d-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-build-m9flflvy/cryptography/
You are using pip version 8.1.1, however version 18.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.

**Comment by Ilcyb** [comment]
@Jetereting 
pip3 install -U setuptools
pip3 install -U wheel

**Comment by Jetereting** [comment]
> @Jetereting
> pip3 install -U setuptools
> pip3 install -U wheel

```
root@ubuntu:~/dev/iysql# pip3 install -U setuptools
Collecting setuptools
  Downloading https://files.pythonhosted.org/packages/82/a1/ba6fb41367b375f5cb653d1317d8ca263c636cff6566e2da1b0da716069d/setuptools-40.5.0-py2.py3-none-any.whl (569kB)
    100% |████████████████████████████████| 573kB 49kB/s 
Installing collected packages: setuptools
  Found existing installation: setuptools 20.7.0
    Not uninstalling setuptools at /usr/lib/python3/dist-packages, outside environment /usr
Successfully installed setuptools-40.5.0
You are using pip version 8.1.1, however version 18.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
root@ubuntu:~ /dev/iysql# pip3 install -U wheel
Collecting wheel
  Downloading https://files.pythonhosted.org/packages/5a/9b/6aebe9e2636d35d1a93772fa644c828303e1d5d124e8a88f156f42ac4b87/wheel-0.32.2-py2.py3-none-any.whl
Installing collected packages: wheel
  Found existing installation: wheel 0.29.0
    Not uninstalling wheel at /usr/lib/python3/dist-packages, outside environment /usr
Successfully installed wheel-0.32.2
You are using pip version 8.1.1, however version 18.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
root@ubuntu:/dev/iysql# ./scripts/init.sh
```

然后：
```
Command "/usr/bin/python3 -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-d01i06r0/cryptography/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-ktrj5_z2-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-build-d01i06r0/cryptography/
You are using pip version 8.1.1, however version 18.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
```

**Comment by Jetereting** [comment]
I run :
```
sudo apt-get install python-pip python-dev libffi-dev libssl-dev libxml2-dev libxslt1-dev libjpeg8-dev zlib1g-dev
```
Solved
