### ISSUE TITLE
Check install environment

### ISSUE THREAD

**Issue by sona201** [influx-code/iysql#6]
![image](https://user-images.githubusercontent.com/25734925/47692932-8a34ed00-dc32-11e8-93eb-6c0b2e9c3754.png)

这里的environment是我哪里搞错了？

**Comment by ty4z2008** [comment]
你配置环境变量了么？
```
alias soar=/root/soft/soar-master/soar
export soar=/root/soft/soar-master/soar
```

**Comment by gangh** [comment]
> ![image](https://user-images.githubusercontent.com/25734925/47692932-8a34ed00-dc32-11e8-93eb-6c0b2e9c3754.png)
> 
> 这里的environment是我哪里搞错了？

查看 init.sh 可知,其中是检查的 soar 这个 cmd 在不在,所以将 soar 所在的位置加入 PATH 即可

执行:
```bash
export PATH="your soar pwd:$PATH"

**Comment by Striver-gjx** [comment]
> 你配置环境变量了么？
> 
> ```
> alias soar=/root/soft/soar-master/soar
> export soar=/root/soft/soar-master/soar
> ```



> 你配置环境变量了么？
> 
> ```
> alias soar=/root/soft/soar-master/soar
> export soar=/root/soft/soar-master/soar
> ```

环境变量是在/etc/profile里面配置嘛?
我的报这个:
soar is not set.Eg:
alias soar=/root/soar
export soar=/root/soar

**Comment by ty4z2008** [comment]
> > 你配置环境变量了么？
> > ```
> > alias soar=/root/soft/soar-master/soar
> > export soar=/root/soft/soar-master/soar
> > ```
> 
> > 你配置环境变量了么？
> > ```
> > alias soar=/root/soft/soar-master/soar
> > export soar=/root/soft/soar-master/soar
> > ```
> 
> 环境变量是在/etc/profile里面配置嘛?
> 我的报这个:
> soar is not set.Eg:
> alias soar=/root/soar
> export soar=/root/soar

你需要配置alias 和export。可以在/etc/profile也可以在~/.bashrc

**Comment by ltxlong** [comment]
我soar和iysql都放在/var/下
export PATH=加了/var/soar
export soar=/var/soar
alias soar=/var/soar

还是报这个:
soar is not set.Eg:
alias soar=/root/soar
export soar=/root/soar

Ubuntu16.04

**Comment by ty4z2008** [comment]
> 我soar和iysql都放在/var/下
> export PATH=加了/var/soar
> export soar=/var/soar
> alias soar=/var/soar
> 
> 还是报这个:
> soar is not set.Eg:
> alias soar=/root/soar
> export soar=/root/soar
> 
> Ubuntu16.04

你在命令行中执行`which soar`看看返回什么。如果是xxx not found所有没有配置好。配置完环境变量之后记得要`source your_environment_file` 
![](https://ws1.sinaimg.cn/large/006tNbRwgy1fx1yj0cxgfj307702l0sv.jpg)

![](https://ws2.sinaimg.cn/large/006tNbRwgy1fx1yknbcotj30er04qaaq.jpg)

**Comment by ltxlong** [comment]
> > 我soar和iysql都放在/var/下
> > export PATH=加了/var/soar
> > export soar=/var/soar
> > alias soar=/var/soar
> > 还是报这个:
> > soar is not set.Eg:
> > alias soar=/root/soar
> > export soar=/root/soar
> > Ubuntu16.04
> 
> 你在命令行中执行`which soar`看看返回什么。如果是xxx not found所有没有配置好。配置完环境变量之后记得要`source your_environment_file`
> ![](https://camo.githubusercontent.com/89c8cdaed9c450ea4efe046f7febeb6efc391f41/68747470733a2f2f7773312e73696e61696d672e636e2f6c617267652f303036744e625277677931667831796a30637867666a3330373730326c3073762e6a7067)
> 
> ![](https://camo.githubusercontent.com/e320ce2a16a7e16f1e274f1a5c563b3dc79032a0/68747470733a2f2f7773322e73696e61696d672e636e2f6c617267652f303036744e625277677931667831796b6e62636f746a333065723034716161712e6a7067)

之前把soar安装在/var/的时候，which soar啥也没返回，我按照你的图，
将soar重新安装在/usr/local/bin/之后，which soar有返回路径了。
之后就是按照/usr/local/bin/soar这个路径配置，但初始化的时候还是出了点问题，pip3报错，我改为pip就行了。不过又有新的错误：

![image](https://user-images.githubusercontent.com/26790349/48262380-44abc780-e45d-11e8-98ed-a474cd7d2445.png)

**Comment by ty4z2008** [comment]
@ltxlong 

我们是基于Python3开发的。你贴一下你的错误

**Comment by ltxlong** [comment]
> @ltxlong
> 
> 我们是基于Python3开发的。你贴一下你的错误

解决了是Python版本的问题，我的Ubuntu默认Python版本是2.7，切换到Python3就好了。
总结如下：
在/usr/local/bin/下安装soar和iysql；（解决which soar没东西的问题）
然后直接export soar=/usr/local/bin/soar；（解决soar is not set.Eg的问题）
然后直接python -V查看Python版本（要求Python3）;
到/usr/bin/备份Python2.7连接并切换到Python3:
sudo cp /usr/bin/python /usr/bin/python_bak
sudo rm /usr/bin/python
sudo ln -s /usr/bin/python3 /usr/bin/python
python -V查看是否切换成功；
然后切换到/usr/local/bin/iysql/目录下（必须）；
然后执行pip install -U pip；（解决You are using pip version 8.1.1, however version 18.1 is available）
执行./scripts/init.sh；（不能直接切换到scripts目录下运行，必须在iysql目录下用./scripts/来调用运行）
执行./scripts/start.sh；（成功，完成）

SQLAdvisor也是一样的操作。

**Comment by Tneciv** [comment]
![image](https://user-images.githubusercontent.com/7685451/48928947-f0095180-ef1e-11e8-85d6-16c79965abd4.png)
配置了环境变量还是不行
