### ISSUE TITLE
add setup.py 

### ISSUE THREAD

**Issue by gangh** [influx-code/iysql#7]
reorganize structure , for easier install

**Comment by Ilcyb** [comment]
@gangh 
添加了setup.py也会有soar和sqladvisor的安装问题，所以我觉得支持以docker方式运行可能会好一些

**Comment by gangh** [comment]
> @gangh
> 添加了setup.py也会有soar和sqladvisor的安装问题，所以我觉得支持以docker方式运行可能会好一些

这是两个打包层次上的问题,可以不用环境变量,使用配置文件里指定所需第三方模块的位置
这样就也可以传到 pypi 上都方便用,也方便标签说明

docker 的镜像也需要,可以直接在 soar 镜像上的基础上再使用 pypi 上的该包来编

**Comment by gangh** [comment]
好像 dockerhub 上连 soar 的镜像也还没有.......我先编个 soar 的吧

**Comment by Ilcyb** [comment]
@gangh 其实docker我已经写好了，但是python的依赖太多，生成的docker镜像太大，所以没放出来。正在用go重写，等用go重写完了就直接制作go版本的docker镜像。

**Comment by gangh** [comment]
> @gangh 其实docker我已经写好了，但是python的依赖太多，生成的docker镜像太大，所以没放出来。正在用go重写，等用go重写完了就直接制作go版本的docker镜像。

我这打了个后面只接 soar 的,大约 71MB,还可以接受, SQLAdvisor 编译依赖占用的空间太多?
