### ISSUE TITLE
Permision denied

### ISSUE THREAD

**Issue by zhangchangwei** [influx-code/iysql#8]
执行sql报错permision denied,直接使用soar执行没问题，不知道是哪里配置不对还是什么原因

**Comment by Ilcyb** [comment]
@zhangchangwei 
你直接用用soar执行的时候用的机器和你安装iysql的机器是同一台吗？

**Comment by zhangchangwei** [comment]
> @zhangchangwei
> 你直接用用飙升执行的时候用的机器和你安装iysql的机器是同一台吗？

是同一台机器

**Comment by zhangchangwei** [comment]
@Ilcyb 是同一台机器

**Comment by 90wukai** [comment]
@zhangchangwei 你直接使用soar执行的时候参数跟iysql不一样，permision denied是soar需要对数据库有建库（临时库）的权限

**Comment by zhangchangwei** [comment]
@90wukai 单独使用soar执行是没有报错的，在iysql才报的，而且用户也都是使用root管理员用户

**Comment by ty4z2008** [comment]
这个是因为Linux下面无执行的权限。iysql是以什么权限运行的？
1. `ls -al` 检查soar是什么权限
2. `iysql`的权限需要与soar的权限一致，因为是内部调用soar执行程序

**Comment by zhangchangwei** [comment]
@ty4z2008 全部授予了777权限，以root最高权限运行

**Comment by zhangchangwei** [comment]
@ty4z2008 我似乎知道什么原因了，iysql调soar命令路径没有找对，但系统环境变量我设置过了，soar可以直接调用，为啥iysql要去找绝对路径嘞？

**Comment by zhangchangwei** [comment]
想知道为什么iysql调用soar命令没有直接使用系统设置的环境变量soar而是找的绝对路径，但绝对路径只到了soar命令的上级目录，导致找不到

**Comment by zhangchangwei** [comment]
可以了，感谢各位，由于环境变量问题

**Comment by ty4z2008** [comment]
> 想知道为什么iysql调用soar命令没有直接使用系统设置的环境变量soar而是找的绝对路径，但绝对路径只到了soar命令的上级目录，导致找不到

命令查找的方式是遵循Linux的命令查找方式的，首先会检查环境变量，然后查找/usr/bin/或/usr/sbin等目录。如果无法找到就会提示。iysql内部也是通过执行soar的命令
