### ISSUE TITLE
Error: No available formula with the name "python3-pip"

### ISSUE THREAD

**Issue by keji94** [influx-code/iysql#9]
brew install python3-pip python3,输出如下:

Updating Homebrew...
Error: No available formula with the name "python3-pip"
==> Searching for a previously deleted formula (in the last month)...
Warning: homebrew/core is shallow clone. To get complete history run:
  git -C "$(brew --repo homebrew/core)" fetch --unshallow

Error: No previously deleted formula found.
==> Searching for similarly named formulae...
Error: No similarly named formulae found.
==> Searching taps...
==> Searching taps on GitHub...
Error: No formulae found in taps.

**Comment by Ilcyb** [comment]
对于macos用户来说，不需要单独安装pip3，只需要执行`brew install python3`即可
